title: climepi
theme: jekyll-theme-cayman
description: "Python package and web app for integrating climate data into epidemiological models"
navigation:
  - name: Home
    link: https://will-s-hart.github.io/climate-epidemics/
  - name: Web app
    link: https://will-s-hart.github.io/climate-epidemics/app
  - name: Python package documentation
    link: https://climate-epidemics.readthedocs.io/en/latest/
