title: climepi web app
theme: jekyll-theme-cayman
navigation:
  - name: Python package documentation
    link: https://climate-epidemics.readthedocs.io/en/latest/
exclude:
  - .vscode/
  - .coverage
  - coverage.xml
  - climepi/
  - climepi.egg-info/
  - data/
  - docs/
  - tests/
  - .pixi/
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from