name: climepi
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Core
  - python>=3.8,<3.12
  - pip
  # climepi dependencies (should match dependencies in pyproject.toml)
  - numpy
  - scipy
  - pandas
  - xarray
  - bottleneck
  - cftime
  - nc-time-axis
  - dask
  - netcdf4
  - pint
  - pint-xarray
  - cf_xarray
  - xcdat
  - clisops
  - flox
  - geopy
  - cartopy
  - hvplot
  - geoviews
  - panel
  - param
  - parfive
  - pooch
  - siphon
  # This package
  - pip:
    - xclim>=0.45 #macos not finding version >0.42 in conda-forge
    - -e .
  # Linting
  - flake8
  - flake8-black
  - flake8-bugbear
  # Testing
  - pytest
  - pytest-cov
  # Documentation
  - sphinx<7.0.0 #bug with v7 using sphinx-book-theme https://github.com/executablebooks/sphinx-book-theme/issues/749
  - sphinx-book-theme
  - sphinx-autosummary-accessors
  # Example notebooks
  - jupyter
  - jupyter_bokeh