# To create, run "conda env create -f environment.yml"
# Run "conda activate climepi", then install the climepi package in development mode with "pip install -e ."

name: climepi
channels:
  - conda-forge
dependencies:
  - python
  - jupyter
  - pip
  - numpy
  - scipy
  - pandas
  - xarray
  - dask
  - pint
  - netcdf4
  - pint-xarray
  - cf_xarray
  - xclim>=0.45
  - clisops
  - flox
  - matplotlib
  - cartopy
  - hvplot
  - geoviews