name: climepi
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Core
  - python
  - pip
  # climepi dependencies (should match dependencies in pyproject.toml)
  - bottleneck
  - dask
  - flox
  - geopy
  - geoviews  
  - hvplot
  - intake
  - intake-esm  
  - nc-time-axis
  - numpy
  - pandas
  - panel
  - param
  - pooch
  - requests
  - s3fs # needed when using intake-esm to access CESM data on AWS server
  - urllib3
  - xarray!=2024.10.0 #awaiting fix for bug in polyfit/polyval https://github.com/pydata/xarray/issues/9690
  - xcdat
  # This package
  - pip:
    - -e .
  # Versioning
  - versioneer
  # Linting
  - ruff
  # Testing
  - pytest
  - pytest-cov
  # Documentation
  - sphinx-book-theme
  - sphinx-autosummary-accessors
  # Example notebooks
  - ipykernel
  - jupyter_bokeh