name: climepi
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Core
  - python
  - pip
  # climepi dependencies (should match dependencies in pyproject.toml)
  - xcdat
  - bottleneck
  - flox
  - geopy
  - hvplot
  - geoviews
  - nc-time-axis
  - panel
  - pooch
  - intake-esm
  - s3fs # needed when using intake-esm to access CESM data on AWS server
  - pip:
    - isimip-client
  # This package
  - pip:
    - -e .
  # Linting
  - ruff
  # Testing
  - pytest
  - pytest-cov
  # Documentation
  - sphinx-book-theme
  - sphinx-autosummary-accessors
  # Example notebooks
  - ipykernel
  - jupyter_bokeh