name: climepi
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Core
  - python>=3.8
  - pip
  # climepi dependencies (should match dependencies in pyproject.toml)
  - xcdat<0.6.1 #0.6.1 requires xesmf, which complicates Windows installation (may revisit in future)
  - xclim>=0.45
  - bottleneck
  - flox
  - geopy
  - hvplot
  - geoviews
  - nc-time-axis
  - panel
  - pooch
  - intake-esm
  - s3fs # needed when using intake-esm to access CESM data on AWS server
  # This package
  - pip:
    - -e .
  # Linting
  - flake8
  - flake8-black
  - flake8-bugbear
  # Testing
  - pytest
  - pytest-cov
  # Documentation
  - sphinx-book-theme
  - sphinx-autosummary-accessors
  # Example notebooks
  - jupyter_bokeh