name: climepi
channels:
  - conda-forge
  - nodefaults
dependencies:
  # Core
  - python>=3.8,<3.12
  - pip
  # climepi dependencies (should match dependencies in pyproject.toml)
  - xcdat
  - xclim>=0.45
  - bottleneck
  - flox
  - geopy
  - hvplot
  - geoviews
  - nc-time-axis
  - panel
  - pooch
  - intake-esm
  # This package
  - pip:
    - -e .
  # Linting
  - flake8
  - flake8-black
  - flake8-bugbear
  # Testing
  - pytest
  - pytest-cov
  # Documentation
  - sphinx<7.0.0 #bug with v7 using sphinx-book-theme https://github.com/executablebooks/sphinx-book-theme/issues/749
  - sphinx-book-theme
  - sphinx-autosummary-accessors
  # Example notebooks
  - jupyter
  - jupyter_bokeh