name: climepi
channels:
  - conda-forge
dependencies:
  # Core
  - python=3.11
  - pip
  # climepi dependencies (should match dependencies in pyproject.toml)
  - numpy
  - scipy
  - pandas
  - xarray
  - bottleneck
  - cftime
  - nc-time-axis
  - dask
  - netcdf4
  - pint
  - pint-xarray
  - cf_xarray
  - xcdat
  - xclim>=0.45
  - clisops
  - flox
  - matplotlib
  - cartopy
  - hvplot
  - geoviews
  # Packages for testing
  - flake8
  - pytest
  - pyest-cov
  # Packages for example notebooks
  - jupyter
  - jupyter_bokeh

# To create, run "conda env create -f environment.yml"
# Run "conda activate climepi", then install the climepi package in development mode with "pip install -e ."
